# Generated by Django 2.2.2 on 2019-06-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190610_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
